name: C++ CI-CD

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "ğŸ§º Set up Environment"
        run: |
          apt update && apt install -y wget cmake bison flex git
      - name: "ğŸµ Install third-party"
        run: |
          cd tools/scripts && ./InstallDep.sh
      - name: "ğŸ  Build"
        run: |
          mkdir build && cd build && cmake .. && make -j
      - name: "ğŸ“¦ Stage"
        run: |
          mkdir staging
          cp bin/* staging
          cp -r resource staging
      - name: "ğŸš€ Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.RELEASE_VERSION }}"
          prerelease: false
          title: "Release ${{ env.RELEASE_VERSION }}"
          files: |
            staging/*
